---
galaxy_info:
  author: Deepak Kumaran T S
  description: /tmp and /dev/shm mounted nosuid,nodev,noexec
  license: MIT
  min_ansible_version: "2.21"
  platforms:
    - name: Ubuntu
      versions:
        - noble
dependencies: []
