"""Write inventory/lab.yml and .lab/ssh_config from the running Multipass VMs.

The inventory is also the allowlist for simulation targets (CLAUDE.md rule 1),
so this script fails closed: it only writes lab VMs that are running, have a
private IPv4 address, and sit inside one lab network.

Usage: scripts/gen_inventory.py [--controller-ip IP] [--multipass-json FILE]
Env:   LAB_PROFILE (full | small), LAB_CIDR (override the derived network),
       LAB_CONTROLLER_IP (override the detected host address).
"""

import argparse
import ipaddress
import json
import os
import shlex
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

# Inventory group -> VM name, per profile. In the small profile the node
# also plays the monitor, which is weaker (CLAUDE.md section 5).
PROFILES: dict[str, dict[str, str]] = {
    "full": {"node": "ssc-node", "monitor": "ssc-monitor", "attacker": "ssc-attacker"},
    "small": {"node": "ssc-node", "monitor": "ssc-node", "attacker": "ssc-attacker"},
}

HEADER = """\
# Generated by scripts/gen_inventory.py from `multipass list`. Do not edit;
# rerun `make lab-up`. This file is also the allowlist for simulation targets.
"""

Runner = Callable[[list[str]], str]


class InventoryError(Exception):
    """The VMs do not form a lab we can safely write an inventory for."""


def lab_hosts(multipass_json: str, profile: str) -> dict[str, ipaddress.IPv4Address]:
    """Return {vm name: first IPv4} for the lab VMs this profile needs."""
    if profile not in PROFILES:
        raise InventoryError(f"LAB_PROFILE must be full or small, got {profile!r}")
    vms = {vm["name"]: vm for vm in json.loads(multipass_json).get("list", [])}
    hosts: dict[str, ipaddress.IPv4Address] = {}
    for name in dict.fromkeys(PROFILES[profile].values()):
        vm = vms.get(name)
        if vm is None:
            raise InventoryError(f"{name} does not exist. Run `make lab-up`.")
        if vm.get("state") != "Running":
            raise InventoryError(f"{name} is {vm.get('state')}, not Running.")
        ipv4 = [
            a
            for a in vm.get("ipv4", [])
            if isinstance(ipaddress.ip_address(a), ipaddress.IPv4Address)
        ]
        if not ipv4:
            raise InventoryError(f"{name} has no IPv4 address yet.")
        address = ipaddress.IPv4Address(ipv4[0])
        if not address.is_private:
            raise InventoryError(
                f"{name} has non-private address {address}; refusing to treat it as lab."
            )
        hosts[name] = address
    return hosts


def lab_network(
    hosts: dict[str, ipaddress.IPv4Address], override: str | None = None
) -> ipaddress.IPv4Network:
    """The lab network: LAB_CIDR if set, else the /24 around the node.

    `multipass list` gives addresses but no netmask, so the /24 is a choice,
    checked against every lab VM.
    """
    if override:
        network = ipaddress.IPv4Network(override, strict=True)
    else:
        network = ipaddress.IPv4Network(f"{hosts['ssc-node']}/24", strict=False)
    if not network.is_private:
        raise InventoryError(f"lab network {network} is not private.")
    outside = [f"{n} ({a})" for n, a in hosts.items() if a not in network]
    if outside:
        raise InventoryError(
            f"not inside {network}: {', '.join(outside)}. Set LAB_CIDR to override."
        )
    return network


def parse_ssh_connection(text: str) -> ipaddress.IPv4Address | None:
    """Client address from $SSH_CONNECTION ("client port server port")."""
    fields = text.split()
    if len(fields) != 4:
        return None
    try:
        return ipaddress.IPv4Address(fields[0])
    except ValueError:
        return None


def parse_default_route(text: str) -> ipaddress.IPv4Address | None:
    """Gateway from `ip -4 route show default` ("default via X dev ...")."""
    fields = text.split()
    if "via" not in fields or fields.index("via") + 1 >= len(fields):
        return None
    try:
        return ipaddress.IPv4Address(fields[fields.index("via") + 1])
    except ValueError:
        return None


def run_command(cmd: list[str]) -> str:
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout


def detect_controller_ip(run: Runner = run_command) -> tuple[ipaddress.IPv4Address, str]:
    """The address the host uses to reach the VMs, and how it was found.

    First choice: the client address of the SSH session `multipass exec`
    opens, which is exactly the address the firewall must keep allowing.
    Fallback: the node's default gateway, which is the host's bridge address
    on Multipass networks.
    """
    exec_node = ["multipass", "exec", "ssc-node", "--"]
    address = parse_ssh_connection(run([*exec_node, "sh", "-c", 'echo "${SSH_CONNECTION:-}"']))
    if address:
        return address, "SSH_CONNECTION of multipass exec"
    address = parse_default_route(run([*exec_node, "ip", "-4", "route", "show", "default"]))
    if address:
        return address, "node default gateway"
    raise InventoryError("could not detect the controller IP. Set LAB_CONTROLLER_IP.")


def build_inventory(
    hosts: dict[str, ipaddress.IPv4Address],
    profile: str,
    network: ipaddress.IPv4Network,
    controller_ip: ipaddress.IPv4Address,
    admin_user: str,
    root: Path,
) -> dict:
    if controller_ip not in network:
        raise InventoryError(f"controller IP {controller_ip} is not inside {network}.")
    if controller_ip in hosts.values():
        raise InventoryError(f"controller IP {controller_ip} is a lab VM address.")
    lab = root / ".lab"
    ssh_args = " ".join(
        [
            "-o IdentitiesOnly=yes",
            f"-o UserKnownHostsFile={shlex.quote(str(lab / 'known_hosts'))}",
            "-o StrictHostKeyChecking=accept-new",
        ]
    )
    children = {
        group: {"hosts": {name: {"ansible_host": str(hosts[name])}}}
        for group, name in PROFILES[profile].items()
    }
    return {
        "all": {
            "vars": {
                "ansible_user": admin_user,
                "ansible_ssh_private_key_file": str(lab / "keys" / "ssc_admin_ed25519"),
                "ansible_ssh_common_args": ssh_args,
                "ansible_python_interpreter": "/usr/bin/python3",
                "lab_profile": profile,
                "lab_cidr": str(network),
                "lab_controller_ip": str(controller_ip),
            },
            "children": children,
        }
    }


def render_ssh_config(hosts: dict[str, ipaddress.IPv4Address], admin_user: str, root: Path) -> str:
    lab = root / ".lab"
    lines = ["# Generated by scripts/gen_inventory.py. Use: ssh -F .lab/ssh_config ssc-node", ""]
    for name, address in hosts.items():
        lines += [
            f"Host {name}",
            f"  HostName {address}",
            f"  User {admin_user}",
            f'  IdentityFile "{lab / "keys" / "ssc_admin_ed25519"}"',
            "  IdentitiesOnly yes",
            f'  UserKnownHostsFile "{lab / "known_hosts"}"',
            "  StrictHostKeyChecking accept-new",
            "",
        ]
    return "\n".join(lines)


def write_file(path: Path, text: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.tmp")
    tmp.write_text(text)
    tmp.chmod(mode)
    tmp.replace(path)


def main(argv: list[str] | None = None, run: Runner = run_command) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--controller-ip", default=os.environ.get("LAB_CONTROLLER_IP"))
    parser.add_argument("--multipass-json", type=Path, help="read this instead of `multipass list`")
    parser.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    root = args.root.resolve()
    profile = os.environ.get("LAB_PROFILE", "full")
    group_vars = yaml.safe_load((ROOT / "inventory" / "group_vars" / "all.yml").read_text())

    try:
        if args.multipass_json:
            listing = args.multipass_json.read_text()
        else:
            listing = run(["multipass", "list", "--format", "json"])
        hosts = lab_hosts(listing, profile)
        network = lab_network(hosts, os.environ.get("LAB_CIDR"))
        if args.controller_ip:
            controller_ip, how = ipaddress.IPv4Address(args.controller_ip), "override"
        else:
            controller_ip, how = detect_controller_ip(run)
        inventory = build_inventory(
            hosts, profile, network, controller_ip, group_vars["admin_user"], root
        )
    except (InventoryError, ValueError, subprocess.CalledProcessError) as err:
        print(f"gen_inventory: {err}", file=sys.stderr)
        return 1

    body = yaml.safe_dump(inventory, sort_keys=False, default_flow_style=False)
    write_file(root / "inventory" / "lab.yml", HEADER + body, 0o644)
    ssh_config = render_ssh_config(hosts, group_vars["admin_user"], root)
    write_file(root / ".lab" / "ssh_config", ssh_config, 0o600)
    print(f"gen_inventory: wrote inventory/lab.yml ({profile} profile, {network})")
    print(f"gen_inventory: controller IP {controller_ip} ({how})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
