"""Write inventory/lab.yml and .lab/ssh_config from the running Multipass VMs.

The inventory is also the allowlist for simulation targets (CLAUDE.md rule 1),
and lab_cidr feeds the SSH allowlist, so this script fails closed. The lab
network is the network of the host bridge that Multipass created for its own
VMs, narrowed to at most a /24 and inside the RFC 1918 ranges. A private
address alone is not enough: a VM bridged onto a campus network also has one.
Only running lab VMs with an address inside the lab network are written.

Usage: scripts/gen_inventory.py [--controller-ip IP] [--multipass-json FILE]
Env:   LAB_PROFILE (full | small), LAB_CIDR (a narrower network, /24 or smaller),
       LAB_CONTROLLER_IP (override the detected host address).
"""

import argparse
import ipaddress
import json
import os
import platform
import re
import shlex
import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

# Inventory group -> VM name, per profile. In the small profile the node
# also plays the monitor, which is weaker (CLAUDE.md section 5).
PROFILES: dict[str, dict[str, str]] = {
    "full": {"node": "ssc-node", "monitor": "ssc-monitor", "attacker": "ssc-attacker"},
    "small": {"node": "ssc-node", "monitor": "ssc-node", "attacker": "ssc-attacker"},
}

# RFC 1918 ranges, listed explicitly. ipaddress.is_private also covers
# loopback, link-local and benchmark ranges, and its table changed in 3.12.4.
RFC1918 = tuple(ipaddress.IPv4Network(n) for n in ("10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16"))

# Host bridges Multipass creates for its own NAT network: bridge100 and up
# (vmnet on macOS), mpqemubr0 (QEMU driver on Linux), mpbr0 (LXD driver).
MULTIPASS_BRIDGE = re.compile(r"^(bridge1\d\d|mpqemubr0|mpbr0)$")

# The lab network is never wider than this, even when the bridge is.
WIDEST_PREFIX = 24

HEADER = """\
# Generated by scripts/gen_inventory.py from `multipass list`. Do not edit;
# rerun `make lab-up`. This file is also the allowlist for simulation targets.
"""

Runner = Callable[[list[str]], str]


class InventoryError(Exception):
    """The VMs do not form a lab we can safely write an inventory for."""


def lab_key_dir() -> Path:
    """The lab SSH keys, outside the repo. Same path as KEY_DIR in scripts/lab.sh."""
    return Path.home() / ".config" / "ssc-lab" / "keys"


def in_rfc1918(network: ipaddress.IPv4Network) -> bool:
    return any(network.subnet_of(block) for block in RFC1918)


def lab_vms(multipass_json: str, profile: str) -> dict[str, list[ipaddress.IPv4Address]]:
    """Return {vm name: IPv4 addresses} for the running lab VMs this profile needs."""
    if profile not in PROFILES:
        raise InventoryError(f"LAB_PROFILE must be full or small, got {profile!r}")
    vms = {vm["name"]: vm for vm in json.loads(multipass_json).get("list", [])}
    found: dict[str, list[ipaddress.IPv4Address]] = {}
    for name in dict.fromkeys(PROFILES[profile].values()):
        vm = vms.get(name)
        if vm is None:
            raise InventoryError(f"{name} does not exist. Run `make lab-up`.")
        if vm.get("state") != "Running":
            raise InventoryError(f"{name} is {vm.get('state')}, not Running.")
        addresses = [ipaddress.ip_address(a) for a in vm.get("ipv4", [])]
        ipv4 = [a for a in addresses if isinstance(a, ipaddress.IPv4Address)]
        if not ipv4:
            raise InventoryError(f"{name} has no IPv4 address yet.")
        found[name] = ipv4
    return found


def parse_ifconfig(text: str) -> list[tuple[str, ipaddress.IPv4Interface]]:
    """IPv4 interfaces from macOS `ifconfig` ("inet A netmask 0xffffff00")."""
    found = []
    name = ""
    for line in text.splitlines():
        header = re.match(r"^(\S+?): flags=", line)
        if header:
            name = header.group(1)
            continue
        inet = re.match(r"^\s+inet (\S+) netmask (0x[0-9a-fA-F]{8})\b", line)
        if inet and name:
            prefix = bin(int(inet.group(2), 16)).count("1")
            found.append((name, ipaddress.IPv4Interface(f"{inet.group(1)}/{prefix}")))
    return found


def parse_ip_addr(text: str) -> list[tuple[str, ipaddress.IPv4Interface]]:
    """IPv4 interfaces from Linux `ip -4 -o addr show` ("3: br0    inet A/24 ...")."""
    found = []
    for line in text.splitlines():
        match = re.match(r"^\d+:\s+(\S+)\s+inet\s+(\S+)", line)
        if match:
            name = match.group(1).split("@")[0]
            found.append((name, ipaddress.IPv4Interface(match.group(2))))
    return found


def host_interfaces(
    run: Runner, system: str | None = None
) -> list[tuple[str, ipaddress.IPv4Interface]]:
    """IPv4 interfaces on the controller (this host)."""
    system = system or platform.system()
    if system == "Darwin":
        return parse_ifconfig(run(["/sbin/ifconfig"]))
    if system == "Linux":
        return parse_ip_addr(run(["ip", "-4", "-o", "addr", "show"]))
    raise InventoryError(f"unsupported host OS {system!r}.")


def lab_bridge(
    controller_ip: ipaddress.IPv4Address,
    interfaces: list[tuple[str, ipaddress.IPv4Interface]],
) -> tuple[str, ipaddress.IPv4Network]:
    """The Multipass bridge that holds the controller IP, and its network.

    This is what makes the network a lab: the address sits on a NAT bridge
    that Multipass made on this host, not on a LAN the host is bridged to.
    """
    names = [name for name, iface in interfaces if iface.ip == controller_ip]
    if not names:
        raise InventoryError(f"controller IP {controller_ip} is not an address of this host.")
    for name, iface in interfaces:
        if iface.ip == controller_ip and MULTIPASS_BRIDGE.match(name):
            return name, iface.network
    raise InventoryError(
        f"controller IP {controller_ip} is on {', '.join(names)}, not on a Multipass bridge "
        "(bridge100 and up on macOS, mpqemubr0 or mpbr0 on Linux); refusing to treat it as lab."
    )


def lab_network(
    controller_ip: ipaddress.IPv4Address,
    bridge_network: ipaddress.IPv4Network,
    override: str | None = None,
) -> ipaddress.IPv4Network:
    """The lab network: LAB_CIDR if set, else the bridge network, at most a /24.

    `multipass list` gives addresses but no netmask, so the prefix comes from
    the host bridge. A wider bridge is narrowed to the /24 around the controller.
    """
    if override:
        network = ipaddress.IPv4Network(override, strict=True)
        if network.prefixlen < WIDEST_PREFIX:
            raise InventoryError(
                f"LAB_CIDR {network} is wider than /{WIDEST_PREFIX}; use a narrower network."
            )
        if not network.subnet_of(bridge_network):
            raise InventoryError(f"LAB_CIDR {network} is not inside the bridge {bridge_network}.")
    elif bridge_network.prefixlen < WIDEST_PREFIX:
        network = ipaddress.IPv4Network(f"{controller_ip}/{WIDEST_PREFIX}", strict=False)
    else:
        network = bridge_network
    if not in_rfc1918(network):
        raise InventoryError(f"lab network {network} is not inside the RFC 1918 ranges.")
    if controller_ip not in network:
        raise InventoryError(f"controller IP {controller_ip} is not inside {network}.")
    return network


def lab_hosts(
    vms: dict[str, list[ipaddress.IPv4Address]], network: ipaddress.IPv4Network
) -> dict[str, ipaddress.IPv4Address]:
    """Return {vm name: its address inside the lab network}.

    A VM can have more addresses (docker0, a bridged NIC); only the one on
    the lab network is used.
    """
    hosts: dict[str, ipaddress.IPv4Address] = {}
    for name, addresses in vms.items():
        inside = [a for a in addresses if a in network]
        if not inside:
            listed = ", ".join(str(a) for a in addresses)
            raise InventoryError(f"{name} has no address inside {network} ({listed}).")
        hosts[name] = inside[0]
    return hosts


def parse_ssh_connection(text: str) -> ipaddress.IPv4Address | None:
    """Client address from $SSH_CONNECTION ("client port server port")."""
    fields = text.split()
    if len(fields) != 4:
        return None
    try:
        return ipaddress.IPv4Address(fields[0])
    except ValueError:
        return None


def parse_default_route(text: str) -> ipaddress.IPv4Address | None:
    """Gateway from `ip -4 route show default` ("default via X dev ...")."""
    fields = text.split()
    if "via" not in fields or fields.index("via") + 1 >= len(fields):
        return None
    try:
        return ipaddress.IPv4Address(fields[fields.index("via") + 1])
    except ValueError:
        return None


def run_command(cmd: list[str]) -> str:
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout


def detect_controller_ip(run: Runner = run_command) -> tuple[ipaddress.IPv4Address, str]:
    """The address the host uses to reach the VMs, and how it was found.

    First choice: the client address of the SSH session `multipass exec`
    opens, which is exactly the address the firewall must keep allowing.
    Fallback: the node's default gateway, which is the host's bridge address
    on Multipass networks.
    """
    exec_node = ["multipass", "exec", "ssc-node", "--"]
    address = parse_ssh_connection(run([*exec_node, "sh", "-c", 'echo "${SSH_CONNECTION:-}"']))
    if address:
        return address, "SSH_CONNECTION of multipass exec"
    address = parse_default_route(run([*exec_node, "ip", "-4", "route", "show", "default"]))
    if address:
        return address, "node default gateway"
    raise InventoryError("could not detect the controller IP. Set LAB_CONTROLLER_IP.")


def build_inventory(
    hosts: dict[str, ipaddress.IPv4Address],
    profile: str,
    network: ipaddress.IPv4Network,
    controller_ip: ipaddress.IPv4Address,
    admin_user: str,
    root: Path,
) -> dict:
    if controller_ip not in network:
        raise InventoryError(f"controller IP {controller_ip} is not inside {network}.")
    if controller_ip in hosts.values():
        raise InventoryError(f"controller IP {controller_ip} is a lab VM address.")
    lab = root / ".lab"
    ssh_args = " ".join(
        [
            "-o IdentitiesOnly=yes",
            f"-o UserKnownHostsFile={shlex.quote(str(lab / 'known_hosts'))}",
            "-o StrictHostKeyChecking=accept-new",
        ]
    )
    children = {
        group: {"hosts": {name: {"ansible_host": str(hosts[name])}}}
        for group, name in PROFILES[profile].items()
    }
    return {
        "all": {
            "vars": {
                "ansible_user": admin_user,
                "ansible_ssh_private_key_file": str(lab_key_dir() / "ssc_admin_ed25519"),
                "ansible_ssh_common_args": ssh_args,
                "ansible_python_interpreter": "/usr/bin/python3",
                "lab_profile": profile,
                "lab_cidr": str(network),
                "lab_controller_ip": str(controller_ip),
            },
            "children": children,
        }
    }


def render_ssh_config(hosts: dict[str, ipaddress.IPv4Address], admin_user: str, root: Path) -> str:
    lab = root / ".lab"
    lines = ["# Generated by scripts/gen_inventory.py. Use: ssh -F .lab/ssh_config ssc-node", ""]
    for name, address in hosts.items():
        lines += [
            f"Host {name}",
            f"  HostName {address}",
            f"  User {admin_user}",
            f'  IdentityFile "{lab_key_dir() / "ssc_admin_ed25519"}"',
            "  IdentitiesOnly yes",
            f'  UserKnownHostsFile "{lab / "known_hosts"}"',
            "  StrictHostKeyChecking accept-new",
            "",
        ]
    return "\n".join(lines)


def write_file(path: Path, text: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(f".{path.name}.tmp")
    tmp.write_text(text)
    tmp.chmod(mode)
    tmp.replace(path)


def main(argv: list[str] | None = None, run: Runner = run_command) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--controller-ip", default=os.environ.get("LAB_CONTROLLER_IP"))
    parser.add_argument("--multipass-json", type=Path, help="read this instead of `multipass list`")
    parser.add_argument("--root", type=Path, default=ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    root = args.root.resolve()
    profile = os.environ.get("LAB_PROFILE", "full")
    group_vars = yaml.safe_load((ROOT / "inventory" / "group_vars" / "all.yml").read_text())

    try:
        if args.multipass_json:
            listing = args.multipass_json.read_text()
        else:
            listing = run(["multipass", "list", "--format", "json"])
        vms = lab_vms(listing, profile)
        if args.controller_ip:
            controller_ip, how = ipaddress.IPv4Address(args.controller_ip), "override"
        else:
            controller_ip, how = detect_controller_ip(run)
        bridge, bridge_network = lab_bridge(controller_ip, host_interfaces(run))
        network = lab_network(controller_ip, bridge_network, os.environ.get("LAB_CIDR"))
        hosts = lab_hosts(vms, network)
        inventory = build_inventory(
            hosts, profile, network, controller_ip, group_vars["admin_user"], root
        )
    except (InventoryError, ValueError, subprocess.CalledProcessError) as err:
        print(f"gen_inventory: {err}", file=sys.stderr)
        return 1

    body = yaml.safe_dump(inventory, sort_keys=False, default_flow_style=False)
    write_file(root / "inventory" / "lab.yml", HEADER + body, 0o644)
    ssh_config = render_ssh_config(hosts, group_vars["admin_user"], root)
    write_file(root / ".lab" / "ssh_config", ssh_config, 0o600)
    print(f"gen_inventory: wrote inventory/lab.yml ({profile} profile, {network})")
    print(f"gen_inventory: controller IP {controller_ip} ({how}) on {bridge}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
